### ISSUE TITLE
Absolute paths in diningAppV2.settings

### ISSUE THREAD

**Issue by ChenJesse** [ChenJesse/diningAppV2#2]
Instead of hardcoding the path of sys.path.import, make it relative

**Comment by ChenJesse** [comment]
theres still some problems with windows computers; for some reason the command doesn't work

**Comment by suchanlee** [comment]
Probably doesn't work because the path strings are different between *unix OS's and Windows. path/to/some/path/ in Windows looks more like path\to\some\path. I recommend using relative paths, with  ``BASE_DIR = os.path.dirname(os.path.dirname(__file__))`` as base dir and using Python's os.path.join from there.
